### PR TITLE
Restore Swift compatibility

### PR DESCRIPTION
**Pull request by BrunoVandekerkhove**
I've tested this one on El Capitan with a very crappy computer. It seems to work fine, I've also included a sample project to make things easier. The podspec and the ReadMe are updated.

### CODE REVIEW

**Comment by iamDecode** [comment]
@BrunoVandekerkhove The swift version in the example seems to differ from the one provided in the library. I can use the example version, but when including the library through cocoa pods from your repository several method and variable names differ, and I get a segmentation fault (related to protocol conformance) when trying to use in implementation.

**Comment by iamDecode** [comment]
@BrunoVandekerkhove additionally, in the swift version the animation when switching views also slides in the content view, in ways that the content view appears behind the toolbar (which looks messy). The obj-c version does not show this behaviour (it only fades in).

**Comment by BrunoVandekerkhove** [comment]
I'll solve it when my computer is repaired (within 2 weeks), only tested this on virtualisation software so couldn't do it properly.

**Comment by BrunoVandekerkhove** [comment]
Accidentally closed it, I'll write a solution when my computer is repaired, should take 2 weeks or so.

**Pull request merged**
