### PR TITLE
Add Swift compatibility

### PR DESCRIPTION
**Pull request by BrunoVandekerkhove**
The CCNPreferencesWindowController for Swift users (I can provide an example project if necessary).

### CODE REVIEW

**Comment by iamDecode** [comment]
Looks good, please merge this @phranck, current CCNPreferencesWindowController is unusable with Swift

**Comment by phranck** [comment]
@BrunoVandekerkhove Thanks for your support! It would be great if you provide an example, too.

**Comment by iamDecode** [comment]
@phranck Could you also update the podspec file? Currently only .h and .m files are included

**Comment by phranck** [comment]
@BrunoVandekerkhove I had updated the podspec, reorganized the entire project and added a new tag due to your Swift support additions. Unfortunately CocoaPods failed on validating the podspec throwing this error:
```
Validating podspec
 -> CCNPreferencesWindowController (1.3.0)
    - ERROR | [OSX] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [OSX] xcodebuild:  CCNPreferencesWindowController/CCNPreferencesWindowController/CCNPreferencesWindowController.swift:67:36: error: use of undeclared type 'ColoredView'
    - ERROR | [OSX] xcodebuild:  CCNPreferencesWindowController/CCNPreferencesWindowController/CCNPreferencesWindowController.swift:67:24: error: 'weak' cannot be applied to non-class type '<<error type>>'

[!] The podspec does not validate.
```
I would kike you to fix this issue and provide a proper Swift example, please. Thanks a lot for your support!

**Pull request merged**
